services:
    ollama:
        image: ollama/ollama:latest
        restart: unless-stopped
        ports:
            - 11434:11434
        volumes:
            - ./ollama_data:/root/.ollama

    postgres:
        image: postgres:16-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

    n8n:
        image: n8nio/n8n:latest
        ports:
            - 5678:5678
        environment:
            - DB_TYPE=postgresdb
            - DB_POSTGRESDB_HOST=postgres
            - DB_POSTGRESDB_USER=${POSTGRES_USER}
            - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
            - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
            - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET}
            - N8N_DIAGNOSTICS_ENABLED=false
            - N8N_PERSONALIZATION_ENABLED=false
            - OLLAMA_HOST=${OLLAMA_HOST}
        volumes:
            - ./n8n_data:/home/node/.n8n
        depends_on:
            - ollama
            - postgres
